moderator_color:
  type: string
  default: "silver"
  description: 
    en: "Moderator shield icon color - use hexadecimal code or html color name."

admin_color:
  type: string
  default: "#FFD700"
  description: 
    en: "Admin shield icon color - use hexadecimal code or html color name."
